name: ESLint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install ESLint
      run: npm install eslint

    - name: Run ESLint
      run: npx eslint .
